### ISSUE TITLE
[bug] Example doesn't work

### ISSUE THREAD

**Issue by Miniontoby** [M4xi1m3/numworks.js#6]
**Describe the bug**
The Example doesn't work

**To Reproduce**
1. Clone the repo
2. `npm install`
3. `npm start`

**Expected behavior**
(I guess) that the webserver would need to start

**Screenshots**
![image](https://user-images.githubusercontent.com/47940064/191079233-50765a26-6549-44ff-be4b-72ee73e5f9b6.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: latest (1.2.1)

**Additional context**
```
PS C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js> npm start

> numworks.js@1.2.1 start
> webpack-dev-server --config conf/dev.webpack.config.js

i ｢wds｣: Project is running at http://localhost:3000/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from ./example/
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (C:\Users\Miniontoby\Documents\Programma's\phaser-webroot\numworks.js\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.4.0
```

**Solutions:**
1. replace `var calculator = new Numworks.Recovery();` by `var calculator = new Numworks();` in `example/index.js` (line 4) to see your calculator
2.  Or use https://github.com/UpsilonNumworks/upsilon.js if you use Epsilon or Upsilon as OS

**Comment by Yaya-Cout** [comment]
It's working on up-to-date Arch Linux with Node v18.9.0.
![image](https://user-images.githubusercontent.com/67095734/191074034-b466fad2-162a-49c2-b325-0974a9d50db5.png)

**Comment by Miniontoby** [comment]
And here it doesn't work!

I now have screenshot:
![image](https://user-images.githubusercontent.com/47940064/191079233-50765a26-6549-44ff-be4b-72ee73e5f9b6.png)

**Comment by Miniontoby** [comment]
I might try this... I think this issue is actually not related to this repo but to windows...

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

After: I got it working with this command: `node --openssl-legacy-provider .\node_modules\webpack-dev-server\bin\webpack-dev-server.js --config conf/dev.webpack.config.js`

EDIT: It didn't see my calculator, can this be because I use the default software and not the Omega software?

**Comment by Yaya-Cout** [comment]
Can you try to replace `var calculator = new Numworks.Recovery();` by `var calculator = new Numworks();` in `example/index.js` (line 4) to see your calculator ?

**Comment by Miniontoby** [comment]
> Can you try to replace `var calculator = new Numworks.Recovery();` by `var calculator = new Numworks();` in `example/index.js` (line 4) to see your calculator ?

Does sort of work, cause it says me this after connecting:
```
Status: Connected.
Model: ????
```

**Comment by Yaya-Cout** [comment]
It's working, so.

**Comment by Miniontoby** [comment]
Its no longer: It keeps reseting my calculator

![image](https://user-images.githubusercontent.com/47940064/191307658-8afd6b30-b314-4774-a2ca-9fbb36808f00.png)

**Comment by Yaya-Cout** [comment]
Do you have Epsilon 19 ?

**Comment by Miniontoby** [comment]
> Do you have Epsilon 19 ?

I just downloaded the newest version...

**Comment by Miniontoby** [comment]
> Do you have Epsilon 19 ?

I am running on 19.5.0 ( bb3baa7 )

**Comment by Yaya-Cout** [comment]
Epsilon 19 isn't compatible with NumWorks.js. Can you try with Upsilon.js ? (Upsilon.js is the Upsilon's fork of Numworks.js)

**Comment by Miniontoby** [comment]
Can you send me link to Upsilon.js? I cannot find it on gh...

EDIT I found it: https://github.com/UpsilonNumworks/upsilon.js

**Comment by Miniontoby** [comment]
Oke that one worked!

**Comment by Miniontoby** [comment]
So i got it all working. Maybe it is a good idea to put the Upsilon.js in
the README at a section: 'if your NW reset when you connected it and trying
to read/write to storage, use this fork'

Also before we close tjis issue:
I got this error message when reading and writing to NW: "Start address
0x90000008 outside of memory map bounds" idk what to do with this...

Op wo 21 sep. 2022 12:57 schreef Yaya-Cout ***@***.***>:

**Comment by Miniontoby** [comment]
So i got it all working and added a way to allow running this lib without
webserver just in nodejs. I can share my addition to the code, since I only
set navigator.usb to node-usb's WebUSB (custom one) if it is undefined.

Maybe it is a good idea to put the Upsilon.js in the README at a section:
'if your NW reset when you connected it and trying to read/write to
storage, use this fork'

Also before we close this issue:
I got this message when reading and writing to NW:

"Start address 0x90000008 outside of memory map bounds"

idk what to do with this...

Op ma 19 sep. 2022 19:09 schreef Yaya-Cout ***@***.***>:

**Comment by Yaya-Cout** [comment]
You can now use Upsilon.js's issue tracker. For the error of address, is it with Numwokrs.js or Upsilon.js, with which OS/version.

**Comment by Miniontoby** [comment]
> You can now use Upsilon.js's issue tracker. For the error of address, is it with Numwokrs.js or Upsilon.js, with which OS/version.

Check the https://github.com/UpsilonNumworks/upsilon.js/issues/3 if you want to still help me with this.

Also do you need that code so this thing can run without webserver thingy?
